name: flutter_firebase_template
description: flutter✖︎firebaseのサンプルをまとめたプロジェクト

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # Hooks
  flutter_hooks:

  # Auth
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  flutter_signin_button: ^2.0.0

  # State
  hooks_riverpod:

  # Firebase
  firebase_core:
  firebase_auth:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  cloud_firestore: ^3.4.8


dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  pedantic_mono: any

flutter:
  uses-material-design: true
