name: flutter_firebase_template
description: flutter✖︎firebaseのサンプルをまとめたプロジェクト

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Auth
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0

  # Hooks
  flutter_hooks:

  # State
  hooks_riverpod:

  # Firebase
  firebase_core:
  firebase_auth:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
